### ISSUE TITLE
The lobby buttons are not functioning

### ISSUE THREAD

**Issue by Immortality-IMT** [aflorj/briscola#2]
As I click on the private lobby and public lobby, the buttons do nothing.

**Comment by aflorj** [comment]
The version hosted [here](https://instant-briscola.herokuapp.com) or a local instance? If you are talking about the former, the Heroku removed their free tier so my web app went offline and if you are still accessing it somehow it must be a version that was cashed or something. If you are talking about the latter then make sure both your backend and front end are running.
